# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2affa732fa84f2e2d2c0b00a77c72636d8445b36973ce19257ceef4d079b264d899f63057fd0a6af382e66cec8eb26f91255f0b29d6ed4145541f4beab28e7e4

test:
  secret_key_base: 87cd7774510ce72d0ca665077aec4dbd5e991d1bf4fc399f324c243aec42bc8e7b247572f6611c69739beee6ffa670e3eeffdfe04fe7926045af07380211e8f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
